menu:
  - name: "Křížová cesta"
    url: "zastaveni"
  - name: "Smíření"
    url: "smireni"
  - name: "Mapa"
    url: "mapa"
  - name: "Autor"
    url: "autor"
  - name: "Kontakty"
    url: "kontakty"

post_date_prefix: "Napsáno"
sharing_button_prompt: "Sdílejte:"

social:
    - icon: envelope
      link: mailto:smireni.odpusteni@gmail.com
    - icon: facebook
      link: https://www.facebook.com/profile.php?id=61558121709567