menu:
  - name: "Křížová cesta"
    url: "zastaveni"
  - name: "Smíření"
    url: "smireni"
  - name: "Mapa"
    url: "mapa"
  - name: "Autor"
    url: "autor"
  - name: "Kontakty"
    url: "kontakty"

social:
